"""quark IR — typed, structured, SSA.

See /workspace/quark/QUARK_IR_PROPOSAL.md for the full design.
Phase 1 + 2: data structures, Builder, printer, validator. No lowering yet.
"""

from .builder import Builder
from .lifetime import Lifetime, LifetimeKind
from .module import (
    BufferType,
    Function,
    FunctionAttrs,
    MmaShape,
    Module,
    Param,
    ParamAttrs,
    ScalarType,
    Type,
)
from .op import (
    ArithOp,
    AsyncCopyCommitOp,
    AsyncCopyOp,
    AsyncCopyWaitOp,
    AtomicRmwOp,
    BarrierOp,
    BitcastOp,
    BlockDimOp,
    BlockIdxOp,
    CmpOp,
    ConstOp,
    ConvertOp,
    ForLoopOp,
    FragApplyOp,
    FragConvertOp,
    FragForEachOp,
    FragReduceOp,
    GridDimOp,
    GroupIdOp,
    IfRegionOp,
    LaneIdOp,
    LoadMatrixOp,
    LoadOp,
    MathOp,
    MergeB32Op,
    MmaOp,
    Op,
    PackedConvertOp,
    SelectOp,
    ShuffleOp,
    SmemAllocOp,
    SplitB32Op,
    StoreMatrixOp,
    StoreOp,
    SubgroupBroadcastOp,
    SubgroupIdOp,
    SubgroupReduceOp,
    ThreadIdInGroupOp,
    ThreadIdxOp,
    UnpackedConvertOp,
    VecBuildOp,
    VecExtractOp,
    VecLoadOp,
    VecStoreOp,
    WhileLoopOp,
    YieldOp,
)
from .printer import print_function, print_module, print_op
from .region import Region
from .tensor import FragTensor, GlobalTensor, SharedRegion, Tensor
from .types import DType, MemSpace, ValueShape
from .validator import (
    PerfWarning,  # re-export from new home
    ValidationError,
    validate_function,
    validate_module,
)
from .value import Value, ValueAllocator

__all__ = [
    "ArithOp",
    "AsyncCopyCommitOp",
    "AsyncCopyOp",
    "AsyncCopyWaitOp",
    "AtomicRmwOp",
    "BarrierOp",
    "BitcastOp",
    "BlockDimOp",
    "BlockIdxOp",
    "BufferType",
    "Builder",
    "CmpOp",
    "ConstOp",
    "ConvertOp",
    "DType",
    "ForLoopOp",
    "FragApplyOp",
    "FragConvertOp",
    "FragForEachOp",
    "FragReduceOp",
    "FragTensor",
    "Function",
    "FunctionAttrs",
    "GlobalTensor",
    "GridDimOp",
    "GroupIdOp",
    "IfRegionOp",
    "LaneIdOp",
    "Lifetime",
    "LifetimeKind",
    "LoadMatrixOp",
    "LoadOp",
    "MathOp",
    "MemSpace",
    "MergeB32Op",
    "MmaOp",
    "MmaShape",
    "Module",
    "Op",
    "PackedConvertOp",
    "Param",
    "ParamAttrs",
    "PerfWarning",
    "Region",
    "ScalarType",
    "SelectOp",
    "SharedRegion",
    "ShuffleOp",
    "SmemAllocOp",
    "SplitB32Op",
    "StoreMatrixOp",
    "StoreOp",
    "SubgroupBroadcastOp",
    "SubgroupIdOp",
    "SubgroupReduceOp",
    "Tensor",
    "ThreadIdInGroupOp",
    "ThreadIdxOp",
    "Type",
    "UnpackedConvertOp",
    "ValidationError",
    "Value",
    "ValueAllocator",
    "ValueShape",
    "VecBuildOp",
    "VecExtractOp",
    "VecLoadOp",
    "VecStoreOp",
    "WhileLoopOp",
    "YieldOp",
    "print_function",
    "print_module",
    "print_op",
    "validate_function",
    "validate_module",
]
